name: piano_tiles
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/background.jpg
    - assets/a.wav
    - assets/c.wav
    - assets/e.wav
    - assets/f.wav
    - assets/C2.wav
    - assets/Cs2.wav
    - assets/D2.wav
    - assets/Ds2.wav
    - assets/E2.wav
    - assets/F2.wav
    - assets/Fs2.wav
    - assets/G2.wav
    - assets/Gs2.wav
    - assets/A2.wav
    - assets/As2.wav
    - assets/B2.wav
    - assets/C3.wav
    - assets/Cs3.wav
    - assets/D3.wav
    - assets/Ds3.wav
    - assets/E3.wav
    - assets/F3.wav
    - assets/Fs3.wav
    - assets/G3.wav
    - assets/Gs3.wav
    - assets/A3.wav
    - assets/As3.wav
    - assets/B3.wav
    - assets/C4.wav
    - assets/Cs4.wav
    - assets/D4.wav
    - assets/Ds4.wav
    - assets/E4.wav
    - assets/F4.wav
    - assets/Fs4.wav
    - assets/G4.wav
    - assets/Gs4.wav
    - assets/A4.wav
    - assets/As4.wav
    - assets/B4.wav
    - assets/C5.wav
    - assets/Cs5.wav
    - assets/D5.wav
    - assets/Ds5.wav
    - assets/E5.wav
    - assets/F5.wav
    - assets/Fs5.wav
    - assets/G5.wav
    - assets/Gs5.wav
    - assets/A5.wav
    - assets/As5.wav
    - assets/B5.wav
    - assets/C6.wav
    - assets/Cs6.wav
    - assets/D6.wav
    - assets/Ds6.wav
    - assets/E6.wav
    - assets/F6.wav
    - assets/Fs6.wav
    - assets/G6.wav
    - assets/Gs6.wav
    - assets/A6.wav
    - assets/As6.wav
    - assets/B6.wav
    - assets/C7.wav
    - assets/Cs7.wav
    - assets/D7.wav
    - assets/Ds7.wav
    - assets/E7.wav
    - assets/F7.wav
    - assets/Fs7.wav
    - assets/G7.wav
    - assets/Gs7.wav
    - assets/A7.wav
    - assets/As7.wav
    - assets/B7.wav
    - assets/C8.wav
